// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// ContainsNestedMapApplyConfiguration represents a declarative configuration of the ContainsNestedMap type for use
// with apply.
type ContainsNestedMapApplyConfiguration struct {
	InnerMap map[string]string `json:"innerMap,omitempty"`
}

// ContainsNestedMapApplyConfiguration constructs a declarative configuration of the ContainsNestedMap type for use with
// apply.
func ContainsNestedMap() *ContainsNestedMapApplyConfiguration {
	return &ContainsNestedMapApplyConfiguration{}
}

// WithInnerMap puts the entries into the InnerMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InnerMap field,
// overwriting an existing map entries in InnerMap field with the same key.
func (b *ContainsNestedMapApplyConfiguration) WithInnerMap(entries map[string]string) *ContainsNestedMapApplyConfiguration {
	if b.InnerMap == nil && len(entries) > 0 {
		b.InnerMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.InnerMap[k] = v
	}
	return b
}
