/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// ContainsNestedMapApplyConfiguration represents a declarative configuration of the ContainsNestedMap type for use
// with apply.
type ContainsNestedMapApplyConfiguration struct {
	InnerMap map[string]string `json:"innerMap,omitempty"`
}

// ContainsNestedMapApplyConfiguration constructs a declarative configuration of the ContainsNestedMap type for use with
// apply.
func ContainsNestedMap() *ContainsNestedMapApplyConfiguration {
	return &ContainsNestedMapApplyConfiguration{}
}

// WithInnerMap puts the entries into the InnerMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InnerMap field,
// overwriting an existing map entries in InnerMap field with the same key.
func (b *ContainsNestedMapApplyConfiguration) WithInnerMap(entries map[string]string) *ContainsNestedMapApplyConfiguration {
	if b.InnerMap == nil && len(entries) > 0 {
		b.InnerMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.InnerMap[k] = v
	}
	return b
}
