// Code generated by applyconfiguration. DO NOT EDIT.

package v1

import (
	time "time"
)

// DurationApplyConfiguration represents a declarative configuration of the Duration type for use
// with apply.
//
// Duration has a custom Marshaler but no markers.
// We want the CRD generation to infer type information
// from the go types and ignore the presense of the Marshaler.
type DurationApplyConfiguration struct {
	Value *time.Duration `json:"value,omitempty"`
}

// DurationApplyConfiguration constructs a declarative configuration of the Duration type for use with
// apply.
func Duration() *DurationApplyConfiguration {
	return &DurationApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *DurationApplyConfiguration) WithValue(value time.Duration) *DurationApplyConfiguration {
	b.Value = &value
	return b
}
