/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration. DO NOT EDIT.

package v1

import (
	externalac "sigs.k8s.io/controller-tools/pkg/applyconfiguration/testdata/cronjob/externalac"
)

// EmbeddedExternalSpecApplyConfiguration represents a declarative configuration of the EmbeddedExternalSpec type for use
// with apply.
//
// EmbeddedExternalSpec embeds an external type with json:",inline".
// Used to test the ExternalApplyConfigurations feature.
type EmbeddedExternalSpecApplyConfiguration struct {
	externalac.ExternalDataApplyConfiguration `json:",inline"`
	// Extra is an additional field.
	Extra *string `json:"extra,omitempty"`
}

// EmbeddedExternalSpecApplyConfiguration constructs a declarative configuration of the EmbeddedExternalSpec type for use with
// apply.
func EmbeddedExternalSpec() *EmbeddedExternalSpecApplyConfiguration {
	return &EmbeddedExternalSpecApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *EmbeddedExternalSpecApplyConfiguration) WithKey(value string) *EmbeddedExternalSpecApplyConfiguration {
	b.ExternalDataApplyConfiguration.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *EmbeddedExternalSpecApplyConfiguration) WithValue(value string) *EmbeddedExternalSpecApplyConfiguration {
	b.ExternalDataApplyConfiguration.Value = &value
	return b
}

// WithExtra sets the Extra field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Extra field is set to the value of the last call.
func (b *EmbeddedExternalSpecApplyConfiguration) WithExtra(value string) *EmbeddedExternalSpecApplyConfiguration {
	b.Extra = &value
	return b
}
