/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// EmbeddedStructApplyConfiguration represents a declarative configuration of the EmbeddedStruct type for use
// with apply.
//
// EmbeddedStruct is for testing that embedded struct is handled correctly when it is used through an alias type.
type EmbeddedStructApplyConfiguration struct {
	// FromEmbedded is a field from the embedded struct that was used through an alias type.
	FromEmbedded *string `json:"fromEmbedded,omitempty"`
}

// EmbeddedStructApplyConfiguration constructs a declarative configuration of the EmbeddedStruct type for use with
// apply.
func EmbeddedStruct() *EmbeddedStructApplyConfiguration {
	return &EmbeddedStructApplyConfiguration{}
}

// WithFromEmbedded sets the FromEmbedded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FromEmbedded field is set to the value of the last call.
func (b *EmbeddedStructApplyConfiguration) WithFromEmbedded(value string) *EmbeddedStructApplyConfiguration {
	b.FromEmbedded = &value
	return b
}
