// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// EmpiableObjectApplyConfiguration represents a declarative configuration of the EmpiableObject type for use
// with apply.
type EmpiableObjectApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
	Bar *string `json:"bar,omitempty"`
}

// EmpiableObjectApplyConfiguration constructs a declarative configuration of the EmpiableObject type for use with
// apply.
func EmpiableObject() *EmpiableObjectApplyConfiguration {
	return &EmpiableObjectApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *EmpiableObjectApplyConfiguration) WithFoo(value string) *EmpiableObjectApplyConfiguration {
	b.Foo = &value
	return b
}

// WithBar sets the Bar field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bar field is set to the value of the last call.
func (b *EmpiableObjectApplyConfiguration) WithBar(value string) *EmpiableObjectApplyConfiguration {
	b.Bar = &value
	return b
}
