// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// ExportedStructApplyConfiguration represents a declarative configuration of the ExportedStruct type for use
// with apply.
type ExportedStructApplyConfiguration struct {
	Baz *string `json:"baz,omitempty"`
}

// ExportedStructApplyConfiguration constructs a declarative configuration of the ExportedStruct type for use with
// apply.
func ExportedStruct() *ExportedStructApplyConfiguration {
	return &ExportedStructApplyConfiguration{}
}

// WithBaz sets the Baz field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Baz field is set to the value of the last call.
func (b *ExportedStructApplyConfiguration) WithBaz(value string) *ExportedStructApplyConfiguration {
	b.Baz = &value
	return b
}
