// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// JustNestedObjectApplyConfiguration represents a declarative configuration of the JustNestedObject type for use
// with apply.
type JustNestedObjectApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
	Bar *bool   `json:"bar,omitempty"`
}

// JustNestedObjectApplyConfiguration constructs a declarative configuration of the JustNestedObject type for use with
// apply.
func JustNestedObject() *JustNestedObjectApplyConfiguration {
	return &JustNestedObjectApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *JustNestedObjectApplyConfiguration) WithFoo(value string) *JustNestedObjectApplyConfiguration {
	b.Foo = &value
	return b
}

// WithBar sets the Bar field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bar field is set to the value of the last call.
func (b *JustNestedObjectApplyConfiguration) WithBar(value bool) *JustNestedObjectApplyConfiguration {
	b.Bar = &value
	return b
}
