// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// NestedStructWithSeveralFieldsApplyConfiguration represents a declarative configuration of the NestedStructWithSeveralFields type for use
// with apply.
type NestedStructWithSeveralFieldsApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
	Bar *bool   `json:"bar,omitempty"`
}

// NestedStructWithSeveralFieldsApplyConfiguration constructs a declarative configuration of the NestedStructWithSeveralFields type for use with
// apply.
func NestedStructWithSeveralFields() *NestedStructWithSeveralFieldsApplyConfiguration {
	return &NestedStructWithSeveralFieldsApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *NestedStructWithSeveralFieldsApplyConfiguration) WithFoo(value string) *NestedStructWithSeveralFieldsApplyConfiguration {
	b.Foo = &value
	return b
}

// WithBar sets the Bar field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bar field is set to the value of the last call.
func (b *NestedStructWithSeveralFieldsApplyConfiguration) WithBar(value bool) *NestedStructWithSeveralFieldsApplyConfiguration {
	b.Bar = &value
	return b
}
