// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// NestedObjectApplyConfiguration represents a declarative configuration of the NestedObject type for use
// with apply.
type NestedObjectApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
	Bar *bool   `json:"bar,omitempty"`
}

// NestedObjectApplyConfiguration constructs a declarative configuration of the NestedObject type for use with
// apply.
func NestedObject() *NestedObjectApplyConfiguration {
	return &NestedObjectApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *NestedObjectApplyConfiguration) WithFoo(value string) *NestedObjectApplyConfiguration {
	b.Foo = &value
	return b
}

// WithBar sets the Bar field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bar field is set to the value of the last call.
func (b *NestedObjectApplyConfiguration) WithBar(value bool) *NestedObjectApplyConfiguration {
	b.Bar = &value
	return b
}
