/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration. DO NOT EDIT.

package v1

// NoMarkerJobSpecApplyConfiguration represents a declarative configuration of the NoMarkerJobSpec type for use
// with apply.
//
// NoMarkerJobSpec defines the desired state of NoMarkerJob
type NoMarkerJobSpecApplyConfiguration struct {
	// Suspend tells the controller to suspend the job.
	Suspend *bool `json:"suspend,omitempty"`
}

// NoMarkerJobSpecApplyConfiguration constructs a declarative configuration of the NoMarkerJobSpec type for use with
// apply.
func NoMarkerJobSpec() *NoMarkerJobSpecApplyConfiguration {
	return &NoMarkerJobSpecApplyConfiguration{}
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *NoMarkerJobSpecApplyConfiguration) WithSuspend(value bool) *NoMarkerJobSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
