/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package genall

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestContentEqualIgnoringGenVersion(t *testing.T) {
	tests := []struct {
		name string
		a    string
		b    string
		want bool
	}{
		{
			name: "identical content",
			a:    "foo\nbar\n",
			b:    "foo\nbar\n",
			want: true,
		},
		{
			name: "empty content",
			a:    "",
			b:    "",
			want: true,
		},
		{
			name: "meaningful difference",
			a:    "foo\nbar\n",
			b:    "foo\nbaz\n",
			want: false,
		},
		{
			name: "CRD version annotation only differs",
			a:    "metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.16.0\n  name: foos\n",
			b:    "metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.17.0\n  name: foos\n",
			want: true,
		},
		{
			name: "CRD version annotation differs with meaningful change",
			a:    "metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.16.0\n  name: foos\nspec: old\n",
			b:    "metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.17.0\n  name: foos\nspec: new\n",
			want: false,
		},
		{
			name: "code generated by comment only differs",
			a:    "// Code generated by controller-gen. DO NOT EDIT.\n\npackage v1\n",
			b:    "// Code generated by controller-gen-v2. DO NOT EDIT.\n\npackage v1\n",
			want: true,
		},
		{
			name: "code generated by comment differs with meaningful change",
			a:    "// Code generated by controller-gen. DO NOT EDIT.\n\npackage v1\nvar x = 1\n",
			b:    "// Code generated by controller-gen-v2. DO NOT EDIT.\n\npackage v1\nvar x = 2\n",
			want: false,
		},
		{
			name: "build tag added vs removed",
			a:    "//go:build !ignore_autogenerated\n\npackage v1\n",
			b:    "\npackage v1\n",
			want: true,
		},
		{
			name: "old style build tag added vs removed",
			a:    "// +build !ignore_autogenerated\n\npackage v1\n",
			b:    "\npackage v1\n",
			want: true,
		},
		{
			name: "build tag with extra constraint is meaningful",
			a:    "//go:build !ignore_autogenerated\n\npackage v1\n",
			b:    "//go:build !ignore_autogenerated,linux\n\npackage v1\n",
			want: false,
		},
		{
			name: "version annotation devel vs release",
			a:    "  annotations:\n    controller-gen.kubebuilder.io/version: (devel)\n",
			b:    "  annotations:\n    controller-gen.kubebuilder.io/version: v0.17.0\n",
			want: true,
		},
		{
			name: "regular comment change is meaningful",
			a:    "// This is a comment\nvar x = 1\n",
			b:    "// This is different\nvar x = 1\n",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ContentEqualIgnoringGenVersion([]byte(tt.a), []byte(tt.b))
			if got != tt.want {
				t.Errorf("ContentEqualIgnoringGenVersion() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestSkipUnchangedWriter(t *testing.T) {
	t.Run("creates new file when none exists", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "output.yaml")

		w := &skipUnchangedWriter{
			inner:    OutputToDirectory(dir),
			pkg:      nil,
			itemPath: "output.yaml",
		}

		content := []byte("apiVersion: v1\nkind: Test\n")
		if _, err := w.Write(content); err != nil {
			t.Fatal(err)
		}
		if err := w.Close(); err != nil {
			t.Fatal(err)
		}

		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != string(content) {
			t.Errorf("file content = %q, want %q", got, content)
		}
	})

	t.Run("skips write when content is byte-identical", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "output.yaml")
		content := []byte("apiVersion: v1\nkind: Test\n")

		if err := os.WriteFile(path, content, 0666); err != nil {
			t.Fatal(err)
		}

		origInfo, _ := os.Stat(path)
		origMtime := origInfo.ModTime()
		time.Sleep(50 * time.Millisecond)

		w := &skipUnchangedWriter{
			inner:      OutputToDirectory(dir),
			pkg:        nil,
			itemPath:   "output.yaml",
			oldContent: content,
		}
		if _, err := w.Write(content); err != nil {
			t.Fatal(err)
		}
		if err := w.Close(); err != nil {
			t.Fatal(err)
		}

		newInfo, _ := os.Stat(path)
		if !newInfo.ModTime().Equal(origMtime) {
			t.Errorf("file was modified: mtime changed from %v to %v", origMtime, newInfo.ModTime())
		}
	})

	t.Run("skips write when only version annotation differs", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "output.yaml")
		oldContent := []byte("metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.16.0\n  name: foos\n")
		newContent := []byte("metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.17.0\n  name: foos\n")

		if err := os.WriteFile(path, oldContent, 0666); err != nil {
			t.Fatal(err)
		}

		origInfo, _ := os.Stat(path)
		origMtime := origInfo.ModTime()
		time.Sleep(50 * time.Millisecond)

		w := &skipUnchangedWriter{
			inner:      OutputToDirectory(dir),
			pkg:        nil,
			itemPath:   "output.yaml",
			oldContent: oldContent,
		}
		if _, err := w.Write(newContent); err != nil {
			t.Fatal(err)
		}
		if err := w.Close(); err != nil {
			t.Fatal(err)
		}

		newInfo, _ := os.Stat(path)
		if !newInfo.ModTime().Equal(origMtime) {
			t.Errorf("file was modified: mtime changed from %v to %v", origMtime, newInfo.ModTime())
		}

		got, _ := os.ReadFile(path)
		if string(got) != string(oldContent) {
			t.Errorf("file content changed unexpectedly")
		}
	})

	t.Run("writes when content meaningfully differs", func(t *testing.T) {
		dir := t.TempDir()
		path := filepath.Join(dir, "output.yaml")
		oldContent := []byte("spec: old\n")
		newContent := []byte("spec: new\n")

		if err := os.WriteFile(path, oldContent, 0666); err != nil {
			t.Fatal(err)
		}

		w := &skipUnchangedWriter{
			inner:      OutputToDirectory(dir),
			pkg:        nil,
			itemPath:   "output.yaml",
			oldContent: oldContent,
		}
		if _, err := w.Write(newContent); err != nil {
			t.Fatal(err)
		}
		if err := w.Close(); err != nil {
			t.Fatal(err)
		}

		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != string(newContent) {
			t.Errorf("file content = %q, want %q", got, newContent)
		}
	})
}

func TestIsAutoGeneratedLine(t *testing.T) {
	tests := []struct {
		line string
		want bool
	}{
		{"    controller-gen.kubebuilder.io/version: v0.17.0", true},
		{"    controller-gen.kubebuilder.io/version: (devel)", true},
		{"// Code generated by controller-gen. DO NOT EDIT.", true},
		{"// Code generated by applyconfiguration. DO NOT EDIT.", true},
		{"//go:build !ignore_autogenerated", true},
		{"// +build !ignore_autogenerated", true},
		{"//go:build !ignore_autogenerated && linux", false},
		{"// +build !ignore_autogenerated,linux", false},
		{"// This is a regular comment", false},
		{"package main", false},
		{"var x = 1", false},
		{"  name: foos", false},
	}

	for _, tt := range tests {
		t.Run(tt.line, func(t *testing.T) {
			got := isAutoGeneratedLine(tt.line)
			if got != tt.want {
				t.Errorf("isAutoGeneratedLine(%q) = %v, want %v", tt.line, got, tt.want)
			}
		})
	}
}

func TestWriteFileIfChanged(t *testing.T) {
	t.Run("writes when no old content", func(t *testing.T) {
		var called bool
		written, err := WriteFileIfChanged(nil, []byte("new"), func(content []byte) error {
			called = true
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
		if !written || !called {
			t.Error("expected writeFn to be called for new file")
		}
	})

	t.Run("skips when byte-identical", func(t *testing.T) {
		content := []byte("same")
		written, err := WriteFileIfChanged(content, content, func([]byte) error {
			t.Fatal("writeFn should not be called")
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
		if written {
			t.Error("expected skip for identical content")
		}
	})

	t.Run("skips when only version annotation differs", func(t *testing.T) {
		oldContent := []byte("metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.16.0\n")
		newContent := []byte("metadata:\n  annotations:\n    controller-gen.kubebuilder.io/version: v0.17.0\n")
		written, err := WriteFileIfChanged(oldContent, newContent, func([]byte) error {
			t.Fatal("writeFn should not be called")
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
		if written {
			t.Error("expected skip for version-only diff")
		}
	})

	t.Run("writes empty file when target does not exist", func(t *testing.T) {
		var called bool
		written, err := WriteFileIfChanged(nil, []byte{}, func(content []byte) error {
			called = true
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
		if !written || !called {
			t.Error("expected writeFn to be called for new empty file")
		}
	})

	t.Run("writes when content meaningfully differs", func(t *testing.T) {
		var called bool
		written, err := WriteFileIfChanged([]byte("old"), []byte("new"), func(content []byte) error {
			called = true
			if string(content) != "new" {
				t.Errorf("writeFn got %q, want %q", content, "new")
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
		if !written || !called {
			t.Error("expected writeFn to be called for meaningful change")
		}
	})
}
