//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package simpletypes

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnotherSimple) DeepCopyInto(out *AnotherSimple) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Nums != nil {
		in, out := &in.Nums, &out.Nums
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnotherSimple.
func (in *AnotherSimple) DeepCopy() *AnotherSimple {
	if in == nil {
		return nil
	}
	out := new(AnotherSimple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleType) DeepCopyInto(out *SimpleType) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleType.
func (in *SimpleType) DeepCopy() *SimpleType {
	if in == nil {
		return nil
	}
	out := new(SimpleType)
	in.DeepCopyInto(out)
	return out
}
