// Code generated by controller-gen. DO NOT EDIT.

package cronjob

// ExampleStructApplyConfiguration represents an declarative configuration of the ExampleStruct type for use
// with apply.
type ExampleStructApplyConfiguration struct {
	ExampleField *string `json:"string,omitempty"`
}

// ExampleStructApplyConfiguration constructs an declarative configuration of the ExampleStruct type for use with
// apply.
func ExampleStruct() *ExampleStructApplyConfiguration {
	return &ExampleStructApplyConfiguration{}
}

// WithExampleField sets the ExampleField field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExampleField field is set to the value of the last call.
func (b *ExampleStructApplyConfiguration) WithExampleField(value string) *ExampleStructApplyConfiguration {
	b.ExampleField = &value
	return b
}
