/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package rsm

import (
	"fmt"
	"regexp"
	"slices"

	"sigs.k8s.io/controller-tools/pkg/genall"
	"sigs.k8s.io/controller-tools/pkg/metrics/internal/model"
	"sigs.k8s.io/controller-tools/pkg/metrics/internal/output"
)

const (
	// headerText is the header of the generated configuration.
	headerText = `# Generated by controller-gen
# Generated based on types for resource-state-metrics %s
`

	// aggregateLabel is set on the generated ClusterRole. resource-state-metrics does not ship a
	// ClusterRole using this label. It is a convention which allows to aggregate the generated
	// ClusterRoles into the ClusterRole used by resource-state-metrics via an aggregationRule,
	// like it is done for kube-state-metrics.
	aggregateLabel = "resource-state-metrics/aggregate-to-manager"

	apiVersion = "resource-state-metrics.instrumentation.k8s-sigs.io/v1alpha1"
	kind       = "ResourceMetricsMonitor"

	// defaultName is the name of the generated ResourceMetricsMonitor if none is set.
	defaultName = "resource-metrics"
)

// familyName is the pattern resource-state-metrics requires for the name of a family.
var familyName = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

// Builder builds a ResourceMetricsMonitor for resource-state-metrics.
type Builder struct {
	name      string
	namespace string

	stores []Store
	rbac   output.RBAC
}

var _ output.Builder = &Builder{}

// NewBuilder returns a new Builder for a ResourceMetricsMonitor with the given name and namespace.
// If the name is empty a default name is used. If the namespace is empty it is not set.
func NewBuilder(name, namespace string) *Builder {
	if name == "" {
		name = defaultName
	}
	return &Builder{
		name:      name,
		namespace: namespace,
		stores:    []Store{},
	}
}

// AddResource adds a store for the resource. It returns an error if the metrics of
// the resource don't fulfill the requirements of resource-state-metrics.
func (b *Builder) AddResource(resource model.Resource) error {
	if err := validateLabels(resource); err != nil {
		return err
	}

	store := toStore(resource)

	for _, family := range store.Families {
		if family.Help == "" {
			return fmt.Errorf("metric %q of %s: resource-state-metrics requires the help to be set", family.Name, resource.GroupVersionKind)
		}
		if !familyName.MatchString(family.Name) {
			return fmt.Errorf("metric %q of %s: resource-state-metrics requires the name to match %s", family.Name, resource.GroupVersionKind, familyName)
		}
	}

	b.stores = append(b.stores, store)
	b.rbac.Add(resource)
	return nil
}

// Write writes the ResourceMetricsMonitor to resource-metrics-monitor.yaml and the ClusterRole to rbac.yaml.
func (b *Builder) Write(ctx *genall.GenerationContext) error {
	monitor := ResourceMetricsMonitor{
		APIVersion: apiVersion,
		Kind:       kind,
		Metadata:   ResourceMetricsMonitorMeta{Name: b.name, Namespace: b.namespace},
		Spec: ResourceMetricsMonitorSpec{
			Configuration: Configuration{Stores: b.stores},
		},
	}

	const virtualFilePath = "resource-metrics-monitor.yaml"
	header := fmt.Sprintf(headerText, Version)
	if err := ctx.WriteYAML(virtualFilePath, header, []any{monitor}); err != nil {
		return fmt.Errorf("failed to write YAML to %s: %w", virtualFilePath, err)
	}

	return b.rbac.Write(ctx, map[string]string{aggregateLabel: "true"})
}

// validateLabels checks the names of the labels of the metrics. resource-state-metrics rejects
// duplicate label names and adds some labels to every sample itself. Labels of the markers
// `label` and `labels` having the name of an injected label are dropped, which is
// documented. Labels created from other options are rejected, as they would not be exposed.
func validateLabels(resource model.Resource) error {
	for _, metric := range resource.Metrics {
		names := map[string]struct{}{}
		add := func(option, name string) error {
			if name == "" {
				return fmt.Errorf("metric %q of %s: the name of the label of the option %s must not be empty", metric.Name, resource.GroupVersionKind, option)
			}
			if _, exists := names[name]; exists {
				return fmt.Errorf("metric %q of %s: the label %q is set multiple times, resource-state-metrics requires unique label names", metric.Name, resource.GroupVersionKind, name)
			}
			names[name] = struct{}{}
			return nil
		}
		addOption := func(option, name string) error {
			if isAutoLabel(name) {
				return fmt.Errorf("metric %q of %s: the label %q of the option %s is added by resource-state-metrics to every metric", metric.Name, resource.GroupVersionKind, name, option)
			}
			return add(option, name)
		}

		for _, label := range slices.Concat(resource.Labels, metric.Labels) {
			if isAutoLabel(label.Name) {
				continue
			}
			if err := add("labels", label.Name); err != nil {
				return err
			}
		}

		if metric.KeyLabel != "" {
			if metric.PathKind != model.PathKindMap {
				return fmt.Errorf("metric %q of %s: the option keyLabel can only be used if the path points to a map", metric.Name, resource.GroupVersionKind)
			}
			if err := addOption("keyLabel", metric.KeyLabel); err != nil {
				return err
			}
		}
		if metric.Type == model.MetricTypeStateSet {
			if err := addOption("labelName", metric.LabelName); err != nil {
				return err
			}
		}
	}
	return nil
}
