// Code generated by applyconfiguration. DO NOT EDIT.

package cronjob

// UnexportedStructApplyConfiguration represents a declarative configuration of the UnexportedStruct type for use
// with apply.
type UnexportedStructApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
}

// UnexportedStructApplyConfiguration constructs a declarative configuration of the UnexportedStruct type for use with
// apply.
func UnexportedStruct() *UnexportedStructApplyConfiguration {
	return &UnexportedStructApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *UnexportedStructApplyConfiguration) WithFoo(value string) *UnexportedStructApplyConfiguration {
	b.Foo = &value
	return b
}
