/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ksm

import (
	"fmt"

	"sigs.k8s.io/controller-tools/pkg/genall"
	"sigs.k8s.io/controller-tools/pkg/metrics/internal/model"
	"sigs.k8s.io/controller-tools/pkg/metrics/internal/output"
)

const headerText = `# Generated by controller-gen
# Generated based on types for kube-state-metrics %s
`

// aggregateLabel is set on the generated ClusterRole. kube-state-metrics does not ship a
// ClusterRole using this label. It is a convention which allows to aggregate the generated
// ClusterRoles into the ClusterRole used by kube-state-metrics via an aggregationRule, e.g.:
// https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/observability/kube-state-metrics/rbac-crd-aggregation.yaml
const aggregateLabel = "kube-state-metrics/aggregate-to-manager"

// Builder builds the custom resource state configuration for kube-state-metrics.
type Builder struct {
	// metrics is the custom resource state configuration file, filled with the
	// resources added to the builder.
	metrics CustomResourceStateMetrics
	rbac    output.RBAC
}

var _ output.Builder = &Builder{}

// NewBuilder returns a new Builder.
func NewBuilder() *Builder {
	return &Builder{
		metrics: CustomResourceStateMetrics{
			Spec: CustomResourceStateMetricsSpec{
				Resources: []Resource{},
			},
		},
	}
}

// AddResource adds the resource to the configuration.
func (b *Builder) AddResource(resource model.Resource) error {
	b.metrics.Spec.Resources = append(b.metrics.Spec.Resources, fromModel(resource))
	b.rbac.Add(resource)
	return nil
}

// Write writes the configuration to metrics.yaml and the ClusterRole to rbac.yaml.
func (b *Builder) Write(ctx *genall.GenerationContext) error {
	header := fmt.Sprintf(headerText, Version)

	// Write the rendered yaml to the context which will result in stdout.
	const virtualFilePath = "metrics.yaml"
	if err := ctx.WriteYAML(virtualFilePath, header, []any{b.metrics}, genall.WithTransform(addCustomResourceStateKind)); err != nil {
		return fmt.Errorf("failed to write YAML to %s: %w", virtualFilePath, err)
	}

	return b.rbac.Write(ctx, map[string]string{aggregateLabel: "true"})
}

// addCustomResourceStateKind adds the correct kind because we don't have a correct
// kubernetes-style object as configuration definition.
func addCustomResourceStateKind(obj map[string]any) error {
	obj["kind"] = "CustomResourceStateMetrics"
	return nil
}

// fromModel converts the resource to the configuration of kube-state-metrics.
func fromModel(resource model.Resource) Resource {
	metrics := make([]Generator, 0, len(resource.Metrics))
	for _, metric := range resource.Metrics {
		metrics = append(metrics, generatorFromModel(metric))
	}

	return Resource{
		MetricNamePrefix: resource.NamePrefix,
		GroupVersionKind: GroupVersionKind{
			Group:   resource.GroupVersionKind.Group,
			Version: resource.GroupVersionKind.Version,
			Kind:    resource.GroupVersionKind.Kind,
		},
		Labels:  Labels{LabelsFromPath: labelsFromModel(resource.Labels)},
		Metrics: metrics,
	}
}

func generatorFromModel(metric model.Generator) Generator {
	meta := MetricMeta{
		LabelsFromPath: labelsFromModel(metric.Labels),
		Path:           metric.Path,
	}

	each := Metric{}
	switch metric.Type {
	case model.MetricTypeGauge:
		each.Type = MetricTypeGauge
		each.Gauge = &MetricGauge{
			MetricMeta:   meta,
			ValueFrom:    metric.Value,
			LabelFromKey: metric.KeyLabel,
			NilIsZero:    metric.MissingAsZero,
		}
	case model.MetricTypeInfo:
		each.Type = MetricTypeInfo
		each.Info = &MetricInfo{
			MetricMeta:   meta,
			LabelFromKey: metric.KeyLabel,
		}
	case model.MetricTypeStateSet:
		each.Type = MetricTypeStateSet
		each.StateSet = &MetricStateSet{
			MetricMeta: meta,
			List:       metric.List,
			LabelName:  metric.LabelName,
			ValueFrom:  metric.Value,
		}
	}

	return Generator{
		Name: metric.Name,
		Help: metric.Help,
		Each: each,
	}
}

func labelsFromModel(labels []model.Label) map[string][]string {
	paths := map[string][]string{}
	for _, label := range labels {
		paths[label.Name] = label.Path
	}
	return paths
}
