// Code generated by applyconfiguration. DO NOT EDIT.

package applyconfiguration

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "sigs.k8s.io/controller-tools/pkg/applyconfiguration/testdata/cronjob/api/v1"
	apiv1 "sigs.k8s.io/controller-tools/pkg/applyconfiguration/testdata/cronjob/api/v1/applyconfiguration/api/v1"
	internal "sigs.k8s.io/controller-tools/pkg/applyconfiguration/testdata/cronjob/api/v1/applyconfiguration/internal"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=testdata.kubebuilder.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("AssociativeType"):
		return &apiv1.AssociativeTypeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ContainsNestedMap"):
		return &apiv1.ContainsNestedMapApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CronJob"):
		return &apiv1.CronJobApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CronJobSpec"):
		return &apiv1.CronJobSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CronJobStatus"):
		return &apiv1.CronJobStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Duration"):
		return &apiv1.DurationApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EmbeddedStruct"):
		return &apiv1.EmbeddedStructApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EmpiableObject"):
		return &apiv1.EmpiableObjectApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ExportedStruct"):
		return &apiv1.ExportedStructApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("JustNestedObject"):
		return &apiv1.JustNestedObjectApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MinMaxObject"):
		return &apiv1.MinMaxObjectApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NestedObject"):
		return &apiv1.NestedObjectApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NestedStructWithSeveralFields"):
		return &apiv1.NestedStructWithSeveralFieldsApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Preserved"):
		return &apiv1.PreservedApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("RootObject"):
		return &apiv1.RootObjectApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
