//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by helpgen. DO NOT EDIT.

package metrics

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates custom resource metrics configuration files for resource-state-metrics",
			Details: "(default) or kube-state-metrics.\n\nThis generator is experimental. The markers, the flags and the generated output might change\nincompatibly in any release. It has to be enabled explicitly by setting the experimental flag.",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Experimental": {
				Summary: "enables the experimental metrics generator.",
				Details: "It has to be set to true to acknowledge that markers and output might change incompatibly.",
			},
			"Target": {
				Summary: "selects the metrics implementation to generate the configuration for.",
				Details: "Supported values are resource-state-metrics and kube-state-metrics.\n\nLeft unspecified, the default is resource-state-metrics.",
			},
			"Name": {
				Summary: "is the name of the ResourceMetricsMonitor which gets generated for resource-state-metrics.",
				Details: "It is only supported by the resource-state-metrics target.\n\nLeft unspecified, the default is resource-metrics.",
			},
			"Namespace": {
				Summary: "is the namespace of the ResourceMetricsMonitor which gets generated for resource-state-metrics.",
				Details: "It is only supported by the resource-state-metrics target.\n\nLeft unspecified, the namespace is not set.",
			},
		},
	}
}
