//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by helpgen. DO NOT EDIT.

package metrics

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates kube-state-metrics custom resource configuration files.",
			Details: "This generator is experimental. The markers, the flags and the generated output might change\nincompatibly in any release. It has to be enabled explicitly by setting the experimental flag.",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Experimental": {
				Summary: "enables the experimental metrics generator.",
				Details: "It has to be set to true to acknowledge that markers and output might change incompatibly.",
			},
		},
	}
}
