package rbac_test

import (
	"bytes"
	"fmt"
	"os"

	"github.com/google/go-cmp/cmp"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	rbacv1 "k8s.io/api/rbac/v1"
	"sigs.k8s.io/controller-tools/pkg/genall"
	"sigs.k8s.io/controller-tools/pkg/loader"
	"sigs.k8s.io/controller-tools/pkg/markers"
	"sigs.k8s.io/controller-tools/pkg/rbac"
	"sigs.k8s.io/yaml"
)

var _ = Describe("ClusterRole generated by the RBAC Generator", func() {
	// run this test multiple times to make sure the Rule order is stable.
	const stableTestCount = 5
	for range stableTestCount {
		It("should match the expected result", func() {
			By("switching into testdata to appease go modules")
			cwd, err := os.Getwd()
			Expect(err).NotTo(HaveOccurred())
			Expect(os.Chdir("./testdata")).To(Succeed()) // go modules are directory-sensitive
			defer func() { Expect(os.Chdir(cwd)).To(Succeed()) }()

			By("loading the roots")
			pkgs, err := loader.LoadRoots(".")
			Expect(err).NotTo(HaveOccurred())

			By("registering RBAC rule marker")
			reg := &markers.Registry{}
			Expect(reg.Register(rbac.RuleDefinition)).To(Succeed())

			By("creating GenerationContext")
			ctx := &genall.GenerationContext{
				Collector: &markers.Collector{Registry: reg},
				Roots:     pkgs,
			}

			By("generating a ClusterRole")
			objs, _, err := rbac.GenerateRoles(ctx, "manager-role")
			Expect(err).NotTo(HaveOccurred())

			By("loading the desired YAML")
			expectedFile, err := os.ReadFile("role.yaml")
			Expect(err).NotTo(HaveOccurred())

			By("parsing the desired YAML")
			for i, expectedRoleBytes := range bytes.Split(expectedFile, []byte("\n---\n")) {
				By(fmt.Sprintf("comparing the generated Role and expected Role (Pair %d)", i))
				obj := objs[i]
				switch obj := obj.(type) {
				case rbacv1.ClusterRole:
					var expectedClusterRole rbacv1.ClusterRole
					Expect(yaml.Unmarshal(expectedRoleBytes, &expectedClusterRole)).To(Succeed())
					Expect(obj).To(Equal(expectedClusterRole), "type not as expected, check pkg/rbac/testdata/README.md for more details.\n\nDiff:\n\n%s", cmp.Diff(obj, expectedClusterRole))
				default:
					var expectedRole rbacv1.Role
					Expect(yaml.Unmarshal(expectedRoleBytes, &expectedRole)).To(Succeed())
					Expect(obj).To(Equal(expectedRole), "type not as expected, check pkg/rbac/testdata/README.md for more details.\n\nDiff:\n\n%s", cmp.Diff(obj, expectedRole))
				}
			}

		})
	}

	It("should generate bindings for markers with serviceAccountName", func() {
		By("switching into testdata to appease go modules")
		cwd, err := os.Getwd()
		Expect(err).NotTo(HaveOccurred())
		Expect(os.Chdir("./testdata")).To(Succeed())
		defer func() { Expect(os.Chdir(cwd)).To(Succeed()) }()

		By("loading the roots")
		pkgs, err := loader.LoadRoots(".")
		Expect(err).NotTo(HaveOccurred())

		By("registering RBAC rule marker")
		reg := &markers.Registry{}
		Expect(reg.Register(rbac.RuleDefinition)).To(Succeed())

		By("creating GenerationContext")
		ctx := &genall.GenerationContext{
			Collector: &markers.Collector{Registry: reg},
			Roots:     pkgs,
		}

		By("generating Roles and collecting binding info")
		objs, bindingsByRole, err := rbac.GenerateRoles(ctx, "manager-role")
		Expect(err).NotTo(HaveOccurred())
		Expect(bindingsByRole).NotTo(BeEmpty(), "should have binding info for markers with serviceAccountName")

		By("generating Bindings from collected info")
		bindings := rbac.GenerateBindings(objs, bindingsByRole)
		Expect(bindings).NotTo(BeEmpty())

		By("loading the expected binding YAML")
		expectedFile, err := os.ReadFile("role_binding.yaml")
		Expect(err).NotTo(HaveOccurred())

		By("verifying bindings match expected")
		for i, expectedBindingBytes := range bytes.Split(expectedFile, []byte("\n---\n")) {
			obj := bindings[i]
			switch obj := obj.(type) {
			case rbacv1.ClusterRoleBinding:
				var expected rbacv1.ClusterRoleBinding
				Expect(yaml.Unmarshal(expectedBindingBytes, &expected)).To(Succeed())
				Expect(obj).To(Equal(expected), "ClusterRoleBinding mismatch.\n\nDiff:\n\n%s", cmp.Diff(obj, expected))
			case rbacv1.RoleBinding:
				var expected rbacv1.RoleBinding
				Expect(yaml.Unmarshal(expectedBindingBytes, &expected)).To(Succeed())
				Expect(obj).To(Equal(expected), "RoleBinding mismatch.\n\nDiff:\n\n%s", cmp.Diff(obj, expected))
			}
		}
	})

	It("should fail when serviceAccountNamespace is missing for ClusterRole", func() {
		By("switching into testdata_invalid to appease go modules")
		cwd, err := os.Getwd()
		Expect(err).NotTo(HaveOccurred())
		Expect(os.Chdir("./testdata_invalid")).To(Succeed())
		defer func() { Expect(os.Chdir(cwd)).To(Succeed()) }()

		By("loading the invalid package")
		pkgs, err := loader.LoadRoots(".")
		Expect(err).NotTo(HaveOccurred())

		By("registering RBAC rule marker")
		reg := &markers.Registry{}
		Expect(reg.Register(rbac.RuleDefinition)).To(Succeed())

		By("creating GenerationContext")
		ctx := &genall.GenerationContext{
			Collector: &markers.Collector{Registry: reg},
			Roots:     pkgs,
		}

		By("expecting error when generating roles")
		_, _, err = rbac.GenerateRoles(ctx, "manager-role")
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("serviceAccountNamespace must be specified for cluster-scoped roles"))
	})

	It("should default serviceAccountNamespace to role namespace", func() {
		By("switching into testdata_default to appease go modules")
		cwd, err := os.Getwd()
		Expect(err).NotTo(HaveOccurred())
		Expect(os.Chdir("./testdata_default")).To(Succeed())
		defer func() { Expect(os.Chdir(cwd)).To(Succeed()) }()

		By("loading the package with default namespace")
		pkgs, err := loader.LoadRoots(".")
		Expect(err).NotTo(HaveOccurred())

		By("registering RBAC rule marker")
		reg := &markers.Registry{}
		Expect(reg.Register(rbac.RuleDefinition)).To(Succeed())

		By("creating GenerationContext")
		ctx := &genall.GenerationContext{
			Collector: &markers.Collector{Registry: reg},
			Roots:     pkgs,
		}

		By("generating Roles and collecting binding info")
		objs, bindingsByRole, err := rbac.GenerateRoles(ctx, "manager-role")
		Expect(err).NotTo(HaveOccurred())
		Expect(bindingsByRole).NotTo(BeEmpty())

		By("verifying serviceAccountNamespace defaulted to role namespace")
		bindingInfo := bindingsByRole["myapp:manager-role"]
		Expect(bindingInfo.ServiceAccountName).To(Equal("app-controller"))
		Expect(bindingInfo.ServiceAccountNamespace).To(Equal("myapp"))

		By("generating Bindings")
		bindings := rbac.GenerateBindings(objs, bindingsByRole)
		Expect(bindings).To(HaveLen(1))

		By("verifying RoleBinding has correct namespace")
		binding := bindings[0].(rbacv1.RoleBinding)
		Expect(binding.Namespace).To(Equal("myapp"))
		Expect(binding.Subjects[0].Name).To(Equal("app-controller"))
		Expect(binding.Subjects[0].Namespace).To(Equal("myapp"))
	})

	It("should fail when same roleName has different ServiceAccounts", func() {
		By("switching into testdata_conflict to appease go modules")
		cwd, err := os.Getwd()
		Expect(err).NotTo(HaveOccurred())
		Expect(os.Chdir("./testdata_conflict")).To(Succeed())
		defer func() { Expect(os.Chdir(cwd)).To(Succeed()) }()

		By("loading the conflicting package")
		pkgs, err := loader.LoadRoots(".")
		Expect(err).NotTo(HaveOccurred())

		By("registering RBAC rule marker")
		reg := &markers.Registry{}
		Expect(reg.Register(rbac.RuleDefinition)).To(Succeed())

		By("creating GenerationContext")
		ctx := &genall.GenerationContext{
			Collector: &markers.Collector{Registry: reg},
			Roots:     pkgs,
		}

		By("expecting error when different ServiceAccounts use same roleName")
		_, _, err = rbac.GenerateRoles(ctx, "manager-role")
		Expect(err).To(HaveOccurred())
		Expect(err.Error()).To(ContainSubstring("already has a binding to ServiceAccount"))
		Expect(err.Error()).To(ContainSubstring("Use a different roleName for each ServiceAccount"))
	})
})
