//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by helpgen. DO NOT EDIT.

package rbac

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates ClusterRole objects.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"RoleName": {
				Summary: "sets the name of the generated ClusterRole.",
				Details: "",
			},
			"FileName": {
				Summary: "sets the file name for the generated manifest(s). If not set, defaults to \"role.yaml\".",
				Details: "",
			},
			"HeaderFile": {
				Summary: "specifies the header text (e.g. license) to prepend to generated files.",
				Details: "",
			},
			"Year": {
				Summary: "specifies the year to substitute for \" YEAR\" in the header file.",
				Details: "",
			},
		},
	}
}

func (Rule) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "RBAC",
		DetailedHelp: markers.DetailedHelp{
			Summary: "specifies an RBAC rule to all access to some resources or non-resource URLs.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Groups": {
				Summary: "specifies the API groups that this rule encompasses.",
				Details: "",
			},
			"Resources": {
				Summary: "specifies the API resources that this rule encompasses.",
				Details: "",
			},
			"ResourceNames": {
				Summary: "specifies the names of the API resources that this rule encompasses.",
				Details: "Create requests cannot be restricted by resourcename, as the object's name\nis not known at authorization time.",
			},
			"Verbs": {
				Summary: "specifies the (lowercase) kubernetes API verbs that this rule encompasses.",
				Details: "",
			},
			"URLs": {
				Summary: "URL specifies the non-resource URLs that this rule encompasses.",
				Details: "",
			},
			"Namespace": {
				Summary: "specifies the scope of the Rule.",
				Details: "If not set, the Rule belongs to the generated ClusterRole.\nIf set, the Rule belongs to a Role, whose namespace is specified by this field.",
			},
			"RoleName": {
				Summary: "specifies a custom name for the Role or ClusterRole.",
				Details: "If not set, uses the default roleName from the generator.\nUseful for avoiding name conflicts when the same roleName is used across multiple namespaces.\n\nExample: When using namespace-scoped RBAC markers with kustomize's global namespace transformation,\nmultiple Roles might end up in the same namespace with identical names, causing an \"ID conflict\" error.\nUse roleName to ensure each Role has a unique name:\n\n  // +kubebuilder:rbac:groups=apps,namespace=infrastructure,roleName=infra-manager,resources=deployments,verbs=get;list\n  // +kubebuilder:rbac:groups=\"\",namespace=users,roleName=user-secrets,resources=secrets,verbs=get\n\nThis generates Roles named \"infra-manager\" and \"user-secrets\" instead of both being \"manager-role\".",
			},
		},
	}
}
